### ISSUE TITLE
端口由于某种原因没有突破

### ISSUE THREAD

**Issue by dollonov** [iamlinhui/rpt#2]
我的配置:
Client.yml:
serverIp: f2.russianodes.com
serverPort: 26048(第一个端口)
# TCP时domain可不填写  HTTP时remotePort可不填写
config:
  - proxyType: TCP
    localIp: 192.168.0.154
    localPort: 25565
    remotePort: 25608(第二港口)
    description: minecraft server.

Server.yml:
#服务端绑定IP
serverIp: 0.0.0.0
#服务端与客户端通讯端口
serverPort: 26048(第一个端口)

在程序中:Lighttunnel 类似的配置工作. 

Client logs:https://pastebin.com/ibQm8QTT 
Server logs:https://pastebin.com/BQYftFHb
Server Java 18 
Clinet java 8/17

**Comment by iamlinhui** [comment]
服务端没有配置token吧  我看你服务端的日志  都是授权连接失败

**Comment by iamlinhui** [comment]
@dollonov 

`server.yml`
```yaml
serverIp: 0.0.0.0
serverPort: 26048
token:
  - clientKey: 123456
    minPort: 1
    maxPort: 65535
```

`client.yml`
```yaml
serverIp: f2.russianodes.com
serverPort: 26048 # 客户端和服务端通讯端口
clientKey: 123456

config:
  - proxyType: TCP
    localIp: 192.168.0.154
    localPort: 25565
    remotePort: 25565 # 这个端口是将本地192.168.0.154:25565服务暴露在服务端的端口,可以取1-65535任意都行
    description: minecraft server
```

**Comment by dollonov** [comment]
由于某种原因，你的选择没有帮助
是我干的:https://www.youtube.com/watch?v=oy5X9ze1Pm4

**Comment by iamlinhui** [comment]
f2.russianodes.com:25565 
![image](https://user-images.githubusercontent.com/17065583/176116228-24feaeea-c0d8-4570-82bd-c057108de8df.png)
@dollonov

**Comment by iamlinhui** [comment]
I made the logic of restricting the port to Chinese IP
@dollonov  you can use the lastest server.jar  https://github.com/iamlinhui/rpt/releases/download/2.5.0/rpt-server-2.5.0.jar

**Comment by dollonov** [comment]
> f2.russianodes.com:25565 ![изображение](https://user-images.githubusercontent.com/17065583/176116228-24feaeea-c0d8-4570-82bd-c057108de8df.png) @dollonov

hosting does not have an open 25565
the hosting ports are open:25608/26048,the rest are closed.

**Comment by dollonov** [comment]
> Сделал логику ограничения порта на китайский IP @dollonov вы можете использовать последний server.jar https://github.com/iamlinhui/rpt/releases/download/2.5.0/rpt-server-2.5.0.jar

I used the latest version of the program

**Comment by iamlinhui** [comment]
@dollonov   you need modify client.yml

`client.yml`

```yaml
serverIp: f2.russianodes.com
serverPort: 26048
clientKey: 123456

config:
  - proxyType: TCP
    localIp: 192.168.0.154
    localPort: 25565
    remotePort: 25608
    description: minecraft server
```

after you conncet  `f2.russianodes.com:25608`
